stages:
- build
- release
- deploy
- tag

build:
  stage: build
  only: [master]
  tags: [docker-dind]
  when: manual
  image: gitlab-dreg.nexxera.com/devops/dockerimages/node:14-alpine
  script:
    - export NODE_ENV=production
    - export REACT_APP_API_ENDPOINT={{URL_APP_API_ENDPOINT}}
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  cache:
    paths:
      - node_modules/

release:
  stage: release
  only: [master]
  tags: [docker-dind]
  when: manual
  script:
    - docker build -t git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git-dreg.nexxera.com
    - docker push git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master

deploy to dev:
   stage: deploy
   tags: [ansible-deploy]
   only: [master]
   except: [schedules]
   environment:
       name: unitrier-ui-dev
   when: manual
   script:
    - sed -i 's/gitlab-dreg.nexxera.com/git-dreg.nexxera.com/' /ansible-deploy/hosts
    - sed -r -i 's/^gitlab_registry_password(.*)$/gitlab_registry_password="jygiX2cJtmvsPvEsDHF2"/' /ansible-deploy/hosts
    - sed -r -i 's/^gitlab_registry_username(.*)$/gitlab_registry_username="ansible-deploy-unitrier-ui"/' /ansible-deploy/hosts
    - ansible-playbook /ansible-deploy/site.yml -e deploy_vars=/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_ENVIRONMENT_NAME.yml -e target=dev

deploy to qa:
   stage: deploy
   tags: [ansible-deploy]
   only: [master]
   except: [schedules]
   environment:
       name: unitrier-ui-qa
   when: manual
   script:
    - sed -i 's/gitlab-dreg.nexxera.com/git-dreg.nexxera.com/' /ansible-deploy/hosts
    - sed -r -i 's/^gitlab_registry_password(.*)$/gitlab_registry_password="jygiX2cJtmvsPvEsDHF2"/' /ansible-deploy/hosts
    - sed -r -i 's/^gitlab_registry_username(.*)$/gitlab_registry_username="ansible-deploy-unitrier-ui"/' /ansible-deploy/hosts
    - ansible-playbook /ansible-deploy/site.yml -e deploy_vars=/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_ENVIRONMENT_NAME.yml -e target=qa

tag to production:
  stage: tag
  only: [master]
  tags: [docker-dind]
  when: manual
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git-dreg.nexxera.com
    - docker pull git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master
    - docker tag git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:production
    - docker push git-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:production
    - apk add curl
    - curl -X POST --fail -F token=$RUNNER_TOKEN_TEMPOCERTO -F ref=main --form "variables[name]=unitrier-ui-prd" https://gitlab.nexxera.com/api/v4/projects/2505/trigger/pipeline
